- README.md
- examples/retrieve_customer.js
- package.json
This pull request rename "omise-node" package to just "omise".
Note: please resubmit npm after merge.
> Rename omise-node package to omise

- test/config.js
`sys` module wasn't used in `test/config.js`. Also, `sys` module is deprecated.
There is an ongoing discussion on removing the `sys` module completely in the next major version: nodejs/node#2405.
If you plan on using `sys` functionality, you should switch to the `util` module.
> Do not needlessly require the deprecated `sys` module in `test/config.js`.

- test/test_omise_charges.js
A fix for https://github.com/omise/omise-node/issues/51 issue
Reversable is only for charge that is not captured. So, need to re-order test a bit.
> Re-order for reverse charge test.

- test/test_omise_charges.js
Hi, I fixed the issue that reported by jscs:
```
$ npm run jscs
> omise@0.5.3 jscs /Users/wingyplus/project/me/omise-node
> jscs *.js lib/*.js test/*.js
; and } should have at most 2 line(s) between them at test/test_omise_charges.js :
114 |        done();
115 |      });
116 |    });
---------------^
117 |
118 |
1 code style error found.
```
> Fix jscs issue in test/test_omise_charges.js

- package.json
When try to compile typescript under ./types/example directory,
it's throw an error:
```console
$ ./node_modules/.bin/tsc ./types/examples/as_promises.ts
node_modules/@types/bluebird/index.d.ts(622,33): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(622,72): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(822,39): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(822,78): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(826,27): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(826,65): error TS2304: Cannot find name 'Map'.
```
It happen because of missing `@types/lodash` in dependencies block.
> Add missing @types/lodash

- README.md
I see in the README.md symlink `pre-commit.sh` location to `../../pre-commit.sh`. It's not correct because `pre-commit.sh` live on the root directory of omise-node.
This PR fix the problem I mentioned above.
> Fix pre-commit.sh symlink path in README.md

- index.js
- lib/api.js
- lib/apiResources.js
- test/test_omise_account.js
- test/test_omise_balance.js
- test/test_omise_cards.js
- test/test_omise_charges.js
- test/test_omise_customers.js
- test/test_omise_disputes.js
- test/test_omise_events.js
- test/test_omise_recipients.js
- test/test_omise_refunds.js
- test/test_omise_tokens.js
- test/test_omise_transactions.js
- test/test_omise_transfers.js
It can be remove '.js' suffix because it require js file by default.
> Refactor require module

- types/index.d.ts
Array definition in type definition is incorrect.
They should be declared as
```typescript
const numbers = number[];
```
not
```typescript
const numbers = [number];
```
> Fix incorrect array definition in typescript

- examples/as_promises.js
- examples/create_token.js
- index.js
- lib/api.js
`Buffer` constructor has been deprecated because of security reasons and has been replaced with `Buffer.from`
https://nodesource.com/blog/understanding-the-buffer-deprecation-in-node-js-10/
> Replace deprecated Buffer constructor

- lib/api.js
- test/test_omise_balance.js
Issue: #103 
Handle failed HTTP request by rejecting instead of letting the exception bubbled up.
> [Issue #103] Ensure that failed HTTP request doesn't ruined server

- README.md
- lib/apiResources.js
- lib/resources/Search.js
- package-lock.json
- test/mocks/search_transfer.js
- test/test_omise_search.js
Usage example:
```
const result = await omise.search.list({
scope: "charge",
filters: {
created: "2019-11-01..2019-11-30"
}
});
```
> Add a support for Search API

- types/index.d.ts
Add `omiseVersion?` in IOptions type.
This change enables to write as follow in TypeScript.
```ts
import * as Omise from 'omise';
const omise = Omise({
publicKey: OMISE_CONFIG.PUBLIC_KEY,
secretKey: OMISE_CONFIG.SECRET_KEY,
omiseVersion: '2019-05-29'
});
```
> Enable to give `omiseVersion` option in constructor in TypeScript

- lib/apiResources.js
- lib/resources/Capability.js
- test/mocks/capability_retrieve.js
- test/test_omise_capability.js
- types/index.d.ts
Add support of `capability API`
- added new resource responsible for capability API call.
- updated `index.d.ts`
- added automatic tests
Install `omise-node` library in your project using `NPM` command `npm i git:github.com/omise/omise-node.git#capability-api`
retrieve capabilities using the following code example:
```
const omise = require('omise')({
publicKey: 'pkey_test_XXXXXX',
secretKey: 'skey_test_XXXXXX',
omiseVersion: '2019-05-29'
});
omise.capability.retrieve(function(err, capability) {
console.log(capability);
});
```
check if capabilities are properly displayed.
or use auto-tests - run `npm test`
N/A
Normal
N/A
> Add support of capability api

- types/index.d.ts
Fix for issue #125 
IDE suggests a wrong attribute
Renamed in typescript type information file `index.d.ts` element responsible for `account`
- Install omise node library in your project using command `npm i git:github.com/omise/omise-node.git#fix-typo`
- check if in visual studio correct hint is displayed when using omise library ![image](https://user-images.githubusercontent.com/10651523/82010910-a7f36700-969d-11ea-8681-134089c370c0.png)
N/A
Normal
N/A
> Fix typo: 'account' instead of 'accounts'

- README.md
- lib/apiResources.js
- lib/resources/Charge.js
- package-lock.json
- package.json
- test/mocks/charge_expire.js
- test/test_omise_charges.js
- types/index.d.ts
Add support of account API
- added new resource responsible for a charge expire call.
- updated index.d.ts
- added automatic tests
Expire a charge
```
const omise = require('omise')({
publicKey: 'pkey_test_XXXXXX',
secretKey: 'skey_test_XXXXXX',
omiseVersion: '2019-05-29'
});
omise.charge.expire(charge_id, function(err, charge) {
console.log(charge.expired); // should be true
});
```
check if account are updated.
or use auto-tests - run `npm test`
N/A
Normal
N/A
> Support expire a charge

- .github/workflows/ci.yml
- CHANGELOG.md
- package.json
- types/index.d.ts
- #134 Missing `IRequest`
- #136 Missing `IRefundRequest`
> Enforce type checking during CI build

- types/index.d.ts
Fix For TrueMoney Source Creation :
- TrueMoney source creation needs the phone number in the request params.
> fix(create-source-params): Add phone_number in create source param

- lib/apiResources.js
- types/index.d.ts
* First commit fixes an issue with authentication when trying to get a list of schedules for a customer 
* Later commits add missing TS types for customer and schedules.
* Authentication error returned when trying to get schedules for a customer using `omise.customers.schedules(customerID)`
* This happened because in `apiResources.js`, the `resourceActions` function was taking an `options` argument (which includes private key), but further down in the `schedules` method, a new variable called options was be declared as `var options = `. This variable was hoisted and therefore leaving `options` as `undefined`
* Fixed by remove duplicate options variable, and instead passing `_makeOptions()` as an argument directly which is consistent with the rest of the file
> [Fix] Authentication for customer schedules

- .gitignore
- lib/api.js
- lib/resources/Account.js
- lib/resources/Balance.js
- lib/resources/Capability.js
- lib/resources/Charge.js
- lib/resources/Customer.js
- lib/resources/Dispute.js
- lib/resources/Event.js
- lib/resources/Link.js
- lib/resources/Recipient.js
- lib/resources/Schedule.js
- lib/resources/Search.js
- lib/resources/Source.js
- lib/resources/Token.js
- lib/resources/Transaction.js
- lib/resources/Transfer.js
- package-lock.json
- package.json
- test/mocks/sources_retrieve.js
- test/test_omise_api_resource.js
- test/test_omise_host.js
- test/test_omise_source.js
- types/index.d.ts
Allow hosts config and added missing source retrieve function
[#ENGA3-808](https://opn-ooo.atlassian.net/browse/ENGA3-808)
- Allow hosts config to switch staging url.
```
import Omise from "omise";
const config = {
host: "api.xxxxxxx.co",
vaultHost : "vault.xxxxxxx.co",
publicKey:    "pkey_*****************",
secretKey:    "skey_*****************",
omiseVersion: "2019-05-29",
};
const omise = Omise(config)
```
- Check response is valid json and reject promise if not valid.
- Add types to support hosts
- Added  missing source retrieve function `omise.sources.retrieve('src_xxxxxx')`
> [ENGA3-808] : Allow hosts config

- docs/pull_request_template.md
- lib/api.js
- lib/resources/Account.js
- lib/resources/Balance.js
- lib/resources/Capability.js
- lib/resources/Charge.js
- lib/resources/Customer.js
- lib/resources/Dispute.js
- lib/resources/Event.js
- lib/resources/Link.js
- lib/resources/Recipient.js
- lib/resources/Schedule.js
- lib/resources/Search.js
- lib/resources/Source.js
- lib/resources/Token.js
- lib/resources/Transaction.js
- lib/resources/Transfer.js
- types/index.d.ts
Support secure protocol and user agent in omise config
https://opn-ooo.atlassian.net/browse/ENGA3-846
- Added `docs/pull_request_template.md`
- Added support for `userAgent` in omise config options
- Added support for `OMISE_SECURE_PROTOCOL` env variable to switch over `http` and `https`
`OMISE_SECURE_PROTOCOL=http node main.js` or 
```
var config = {
...
secureProtocol: 'http',
userAgent: 'Shopify-Payments-App/v1.9.1'
};
```
> [ENGA3-846] : Support secure protocol and user agent

- lib/api.js
- types/index.d.ts
Change `secureProtocol` to `scheme`
[ENGA3-907](https://opn-ooo.atlassian.net/browse/ENGA3-907)
```
var config = {
host: 'api.core.svc',
...
scheme: 'http'
};
```
> [ENGA3-907] : change secureProtocol to scheme

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .gitignore
- README.md
- examples/as_promises.js
- package-lock.json
- Added `package-lock.json` back which is generated with node version 12.x
- Update Promise example code
> Added package-lock back

- .eslintrc
- README.md
- lib/api.js
- test/test_omise_account.js
- test/test_omise_account_promise.js
- test/test_omise_api_resource.js
- test/test_omise_balance.js
- test/test_omise_capability.js
- test/test_omise_cards.js
- test/test_omise_charges.js
- test/test_omise_charges_schedules.js
- test/test_omise_customers.js
- test/test_omise_disputes.js
- test/test_omise_events.js
- test/test_omise_host.js
- test/test_omise_links.js
- test/test_omise_recipients.js
- test/test_omise_refunds.js
- test/test_omise_search.js
- test/test_omise_source.js
- test/test_omise_tokens.js
- test/test_omise_transactions.js
- test/test_omise_transfers.js
- test/test_omise_transfers_schedules.js
Support backward compatibility with warning message for handling promise.
Update invalid test cases
- `expect(foo, "bar")` always return true and the correct way is `assert.equal(foo, "bar")`
- `if (err) done(err);` done function must call if there is any error. Otherwise the unit test asserting will be mark as error and not showing the failed result properly.
> Backward compatibility for handling promise

- lib/apiResources.js
Bug fixed for NEXTJS issue
Similar fix of https://github.com/omise/omise-node/pull/166
- Replace array `[].join()` with normal `+` sign to join the string
- Tested on `Next.js 12` and `Next.js 13`.
- Node version : v18.14.0
> Bug fixed for NEXTJS issue

- .github/workflows/coverage.yml
- sonar-project.properties
Fixed Sonarcloud report path in sonar properties file
Related PR - #201 
Will be `93.3%` Estimated after merge
Github action Logs
```
INFO: Sensor JavaScript/TypeScript Coverage [javascript]
INFO: Analysing [/github/workspace/./coverage/lcov.info]
INFO: Sensor JavaScript/TypeScript Coverage [javascript] (done) | time=17ms
```
> Fix Sonarcloud report path

- test/config.js
- test/test_omise_charges.js
- types/index.d.ts
Add a new field `webhook_endpoints` to the `IRequest` of charge.
We can add max 2 endpoints to the `webhook_endpoints` field.
- [] The default rollback procedure can be used. [PCI DSS 6.5.5.4]
- [] There is no business impact planned. [PCI DSS 6.4.5.1]
- [] If this is a significant change, security team have reviewed the change. [PCI DSS 6.4.6]
- [] No manual Pre or Post deployment steps needed.
> Added webhook_endpoints to the request of charge.

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- package-lock.json
- package.json
Fix warning from nyc package
- Update nyc package and move it under dev dependencies.
- Update Github actions version
- Removed [unstable Node versions](https://nodejs.org/en/about/previous-releases) from the Github workflow
default rollback procedure
> Fix warning from nyc package.
