CHANGELOG.md, README.md, lib/apiResources.js, package.json
The fix should correct the missing data for nested resource.
=> Fix nested resource missing data param

examples/list_charges.js, lib/apiResources.js, test/mocks/charges_list.js, test/mocks/charges_list_data.js, test/test_omise_charges.js
This PR is the fix for https://github.com/omise/omise-node/issues/43
=> Add list params

CHANGELOG.md, README.md, lib/apiResources.js, lib/resources/Event.js, package.json, test/mocks/event_retrieve.js, test/mocks/events_list.js, test/test_omise_events.js
=> Support events-api

lib/apiResources.js, test/test_omise_customers.js, test/test_omise_events.js
Basically, merge https://github.com/omise/omise-node/pull/52 and https://github.com/omise/omise-node/pull/53 into 1 PR.
=> Side effect fix

README.md, examples/create_link.js, examples/retrieve_customer.js, lib/apiResources.js, lib/resources/Link.js, package.json, test/mocks/links_create.js, test/mocks/links_list.js, test/mocks/links_retrieve.js, test/test_omise_links.js
- Add support for Link API
- Add Link example & Tests
- Update README
=> Add support for Link API

lib/api.js
Version header should be `Omise-Version` not `omiseVersion`
=> Fix incorrect version header

package.json
Reverts omise/omise-node#71
My bad. I merged the PR without enough investigation
=> Revert "Add missing @types/lodash"

types/index.d.ts
It might be useful if we add response type to `ResponseCallback`. please review.
Thanks
=> Add response type to ResponseCallback

.eslintrc, examples/as_promises.js, examples/create_source.js, lib/api.js, lib/apiResources.js, lib/resources/Source.js, test/mocks/sources_create.js, test/test_omise_source.js, types/examples/create_source.ts, types/index.d.ts
Add the source API and Typescript definition of Source interface
=> Add the source API

README.md
The docs.omese.com currently can't resolve from DNS anymore.
I'm replacing every link to www.omese.com
=> fix all broken link

lib/apiResources.js, lib/resources/Charge.js, lib/resources/Forex.js, lib/resources/Transfer.js
**Forex**
Add a retrieve function
Code:
```
omise.forex.retrieve("usd", function (error, forex) {
console.log(forex);
});
```
Expected Result:
```
{
"object": "forex",
"from": "usd",
"to": "thb",
"rate": 31.5134004,
"location": "/forex/usd"
}
```
**Charges**
Add a schedules function to get a list of charge schedules
Code:
```
omise.charges.schedules({
"from": "",
"limit": "20",
"offset": "0",
"order": "reverse_chronological",
"timezone": "Asia/Bangkok",
"to": ""
}, function (error, schedules) {
console.log(schedules);
});
```
Expected Result:
```
{
"object": "list",
"from": "1970-01-01T00:00:00Z",
"to": "2017-12-22T09:38:09Z",
"offset": 0,
"limit": 20,
"total": 1,
"order": "reverse_chronological",
"location": "/charges/schedules",
"data": [
{
"object": "schedule",
"id": …
```
=> Support Omise's Forex API

lib/api.js, package.json
Will add agent (HttpsProxyAgent) to http request options if http_proxy env variable is present
=> Added option to add Https proxy agent

README.md, circle.yml
Upgrade version of node in Circleci to 4.4.6 to support ES6 syntax
=> Upgrade version of node in cirleci to 4.4.6 (LTS)

test/test_omise_links.js, test/test_omise_source.js
Remove .js from `require` of test cases
=> Remove .js file extension from requires

types/index.d.ts
Add a missing callback parameter to typescript definition file
=> Add missing callback parameter for list customer API

README.md, lib/resources/Recipient.js, lib/resources/Transfer.js, package-lock.json, test/mocks/recipients_schedules_list.js, test/mocks/transfers_schedules_create.js, test/mocks/transfers_schedules_destroy.js, test/mocks/transfers_schedules_list.js, test/mocks/transfers_schedules_retrieve.js, test/testHelper.js, test/test_omise_transfers_schedules.js
1. List all transfer schedules
```
omise.transfers.schedules(function (err, resp) {
/* Response. */
});
```
2. List all transfer schedules for a recipient
```
omise.transfers.schedules("recp_test_58dw0pqszjc9hlv8gbo", function (err, resp) {
/* Response. */
});
```
=> Add transfer schedules

examples/charge_schedule.js, lib/resources/Schedule.js, types/examples/charge_schedule.ts, types/index.d.ts
Add an example of charge scehdule
=> Charge schedule example

lib/api.js, lib/apiResources.js, lib/resources/Account.js, lib/resources/Balance.js, lib/resources/Charge.js, lib/resources/Schedule.js, lib/resources/Token.js, package-lock.json, package.json
Lint the project with eslint and update modules to fix vulnerability issues.
=> Lint project

examples/charge_schedule.js, examples/create_customer.js, examples/create_link.js, package-lock.json, package.json, test/mocks/customer_schedules_list.js
Update version to 0.5.6
- Fix package vulnerabilities by updating `lodash` and `eslint`
=> Bump 0.5.6

.circleci/config.yml, circle.yml
Currently, it uses the old version of CircleCI config. Just updated it.
=> Update CircleCI config

types/index.d.ts
Fixes https://github.com/omise/omise-node/issues/138
=> Add destroy method to Schedules API interface

CHANGELOG.md, package.json
- #137 Add destroy method TS definition for Schedules API
=> Release 0.8.3

lib/api.js, lib/apiResources.js, test/mocks/charges_list_data.js, test/mocks/search_transfer.js
Fix the issue where the library sends GET/DELETE requests with request body. We have to convert request body to query string instead.
=> Fix GET/DELETE requests contain request body

CHANGELOG.md, package.json
* #145  Fix GET/DELETE requests contain request body.
=> Release 0.8.4

CHANGELOG.md, package.json
**v0.8.5**
- Add `phone_number` in source params (#147).
- Fix authentication for customer schedules (#143).
=> Release 0.8.5

types/index.d.ts
Update attributes of all interfaces to be aligned with Omise API 2019-05-29 document.
=> Update interfaces for TypeScript

package.json
Preparing release v0.9.0-alpha.0
=> Preparing release v0.9.0-alpha.0

package.json
Preparing to release v0.9.0-alpha.1
=> Preparing to release v0.9.0-alpha.1

package.json
=>  dump v0.9.0-alpha.2

CHANGELOG.md, package-lock.json, package.json
Bump v0.9.0
- Add support scheme in config [(#175)](https://github.com/omise/omise-node/pull/175)
- Add support host in config [(#169)](https://github.com/omise/omise-node/pull/169)
=> [ENGA3-903] : Bump v0.9.0

examples/as_promises.js, examples/charge_schedule.js, examples/create_customer.js, examples/create_link.js, examples/create_source.js, examples/create_token.js, examples/destroy_customer.js, examples/list_cards.js, examples/list_charges.js, examples/list_customers.js, examples/retrieve_customer.js, examples/update_customer.js
Fixed sonarcloud issue on examples folder
=> Fixed sonarcloud issue on examples folder

lib/logger.js
Fixed security risk on logging 
- replace bearer authorization header with `[REDACTED]`
=> Fixed security risk on logging

CHANGELOG.md, package-lock.json, package.json
=> Bump v0.10.1

types/index.d.ts
***NOTE: Please make sure PR title is of the format [OMISE-1234]***
- ***Should be matched with the associated JIRA ticket being worked on.***
- ***Use upper case only.***
There is a typo in the request interface which causes troubles when using `recipients.create`
=> fix: interface typo

.github/workflows/ci.yml, .github/workflows/coverage.yml, .gitignore, package.json, sonar-project.properties
- Added workflow for Sonarcloud code coverage report and 
- Fixed test workflow running 2 times when PR opened.
=> [MIT-1511] Added workflow for Sonarcloud code coverage report

CHANGELOG.md, package-lock.json, package.json
=> Bump to v0.11.0

README.md
Update omise api version in README.md to avoid old api usage.
=> Updated api version in readme

CHANGELOG.md, package-lock.json, package.json
Update metadata for the release v0.12.0
**What's changed**
- Added support for dynamic webhook [(#207)](https://github.com/omise/omise-node/pull/207)
- Updated api version in readme [(#205)](https://github.com/omise/omise-node/pull/205)
=> Bump v0.12.0

.github/workflows/coverage.yml
SONARCLOUD_TOKEN → SONAR_TOKEN
=> SONARCLOUD_TOKEN → SONAR_TOKEN

CHANGELOG.md, package.json
Metadata updated for the release of v0.12.1
**What's changed**
- Status added to ICharge interface. [(#213)](https://github.com/omise/omise-node/pull/213)
`default rollback procedure`
=> Release v0.12.1
